### ISSUE TITLE
Thema Wizard - Wizard stappen in storybook met voorbeeld themas

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/overheidsbrede-portalen-community#148]
# Description
Als voorwerk op een uiteindelijk theme builder wizard willen we de mogelijke stappen uitwerken in storybook. Dit zorgt ervoor dat we een beeld krijgen van welke stappen goed zouden werken en in welke volgorde. 

## Acceptance criteria
- [x] [Jeffreys builder figma stappen](https://www.figma.com/design/fy08SZpZmqx6ljLwvA3Woe/NLDS---Schetsboek?node-id=2174-39245&node-type=canvas&t=5KsjWWtzaPohKbge-0) in storybook zetten (Font family, kleuren, witruimte, rondingen)
- [x] Themas toevoegen onder stappen als voorbeeld

UPDATE 7 okt: Robbert heeft eind september een een ruw voorbeeld gemaakt m.b.v. Storybook, uiteindelijk moet het een losse app worden.

## Ter info: 
Thema Builder - Figma Design maken op basis van wizard-ontwerp Aline en Jeff #124

**Comment by ux-fran** [comment]
@Marwaxhello @bddjong liet vanmorgen een ruwe opzet van @Robbert zien in Storybook, dat zag er al veelbelovend uit. (Maar wellicht wist je dit al :) )
