### ISSUE TITLE
Thema Builder - Grijs basis thema

### ISSUE THREAD

**Issue by bddjong** [nl-design-system/overheidsbrede-portalen-community#149]
Zie [Basis Thema in Figma](https://www.figma.com/design/W6e1fZMa3sLepOwRbVugjN/NLDS---Basis---Bibliotheek?node-id=197-664&t=iRCTfWkMlRQcreBg-1)

en [JSON](https://github.com/nl-design-system/themes/blob/main/proprietary/basis-design-tokens/figma/basis.tokens.json)

**Comment by ux-fran** [comment]
@Marwaxhello @jeffreylauwers heeft een grijs basisthema  in Tokenstudio gemaakt vorige week, wellicht heb je daar wat aan?
